// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwrV_tBDYRcc1hntHAVpidHRFMhMr2r5k',
    appId: '1:422115951006:android:d2fd9b78a95bec8926568f',
    messagingSenderId: '422115951006',
    projectId: 'we-can-chat-6f548',
    storageBucket: 'we-can-chat-6f548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9vKXZ8no3a_LrDnMOyyMP85hDta8w7ew',
    appId: '1:422115951006:ios:50904cc3940c2a4e26568f',
    messagingSenderId: '422115951006',
    projectId: 'we-can-chat-6f548',
    storageBucket: 'we-can-chat-6f548.appspot.com',
    androidClientId: '422115951006-2hchbuvjvpgah4cnhfbja5kns5l0b4sr.apps.googleusercontent.com',
    iosClientId: '422115951006-dh3sepdnrc4kkab6tbbklviv7uvqvoa0.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
